version: '3.7'

# ==============================
# Extensions
# ==============================
x-container-defaults:
  &defaults
  restart: always
  env_file:
    - .env

#x-backend-container:
#  &backend-defaults
#  build:
#    context: ./backend
#    dockerfile: ./build/Dockerfile
#
#  depends_on:
#    - mongo
#  volumes:
#    - ./backend:/code
#  tty: true
#  stdin_open: true
#  environment:
#    - PYTHONUNBUFFERED=1
#  networks:
#    - default
# ==============================


services:
#  backend:
#    <<: *backend-defaults
#    <<: *defaults
#    ports:
#      - 8000:8000
#    command:
#      - uvicorn
#      - src.api.app:app
#      - --reload
#      - --reload-dir
#      - src/
#      - --host
#      - 0.0.0.0

  mongo:
    <<: *defaults
    image: mongo
    ports:
      - 27017:27017
    volumes:
      - mongo:/data/mongodb
    environment:
      MONGO_INITDB_ROOT_USERNAME: root
      MONGO_INITDB_ROOT_PASSWORD: example

  mongo-express:
    << : *defaults
    image: mongo-express
    ports:
      - 8081:8081
    environment:
      ME_CONFIG_MONGODB_ADMINUSERNAME: root
      ME_CONFIG_MONGODB_ADMINPASSWORD: example


volumes:
  mongo:
